name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: tayadeabhilash
        DOCKER_PASSWORD: dckr_pat_h4oVh9x-WlQabbDvHZOpT7zeaxg
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t tayadeabhilash/skillmatch .
    - name: Push to Dockerhub
      run: docker push tayadeabhilash/skillmatch:latest
